### ISSUE TITLE
o vilao morre no final da temp 6

### ISSUE THREAD

**Issue by VitorMarciano001** [orlandosaraivajr/tutorial_git#2]
contei mesmo

**Comment by orlandosaraivajr** [comment]
Não gostei do seu comentário !

**Comment by Ademar-Altomani** [comment]
Eu já sabia, mas na temporada 7 o vilão na vdd é pai do protagonista

**Comment by orlandosaraivajr** [comment]
![image](https://github.com/orlandosaraivajr/tutorial_git/assets/2480421/56cbeaa6-1d9f-4d4d-bffc-bd985f6e7890)
Como você pode observar, o bug aconteceu na minha máquina

**Comment by jp8002** [comment]
É verdade, mas achei meio zoado que ele volta a vida na temporada 8
