### ISSUE TITLE
Informar o informate

### ISSUE THREAD

**Issue by jonathannrocha** [orlandosaraivajr/tutorial_git#2]

**Comment by orlandosaraivajr** [comment]
Isso pode acontecer constantemente. MAs não na melhor aula de quarta-feira

![Git Diagram](https://github.com/orlandosaraivajr/tutorial_git/assets/2480421/1eedf2a8-8649-46d1-b722-65408e30671c)

**Comment by orlandosaraivajr** [comment]
Concluo essa issue, pois entendo que está tudo ok
